In [2]:
!pip install numpy pandas

import numpy as np
import pandas as pd

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 8.6 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 5.9 MB/s eta 0:00:0000:0100:01


In [58]:
# Import Dataset

In [14]:
dataset = pd.read_csv('datasets/Data.csv')
dataset.info


<bound method NDFrame.describe of    Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes>

In [15]:
dataset.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [54]:
X = dataset.iloc[ : , :-1].values
X[:,1:3]

array([[44.0, 72000.0],
       [27.0, 48000.0],
       [30.0, 54000.0],
       [38.0, 61000.0],
       [40.0, nan],
       [35.0, 58000.0],
       [nan, 52000.0],
       [48.0, 79000.0],
       [50.0, 83000.0],
       [37.0, 67000.0]], dtype=object)

In [17]:
Y = dataset.iloc[ : , 3].values
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [59]:
# Handling the missing data

In [23]:
!pip install sklearn

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.8/30.8 MB 2.8 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.0/307.0 kB 8.4 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.9/43.9 MB 7.2 MB/s eta 0:00:00:00:0100:01
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1304 sha256=9cd2ee72f88cb0b1d0a854d44b600807376349f747f8631076133a5a9ffb8e67
  Stored in directory: /home/cuongnguyen_jack/.cache/pip/wheels/e4/7b/98/b6466d71b8d738a0c547008b9eb39bf8676d1ff6ca4b22af1c
Successfully built sklearn


In [25]:
# Import the simpleImputer class
from sklearn.impute import SimpleImputer

In [47]:
# Imputer object using the mean strategy and missing value type for imputation
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean")


In [55]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [60]:
## fitting X to the imputer object
imputer = imputer.fit(X[:,1:3])

In [61]:
## Imputing the data  
X[:,1:3]=imputer.transform(X[:,1:3])
print("Imputed X: \n", X)

Imputed X: 
 [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [62]:
# Encoding categorical data

In [63]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [64]:
labelencoder_X = LabelEncoder()

In [66]:
X[ : , 0] = labelencoder_X.fit_transform(X[ : , 0])
X[ : , 0]

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=object)

In [67]:
### Creating a dummy variable

In [78]:
from sklearn.compose import ColumnTransformer

In [79]:
ct = ColumnTransformer([('one_hot_encoder', OneHotEncoder(categories='auto'),[0])], remainder = 'passthrough')
X = ct.fit_transform(X)
X

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 

In [80]:
labelencoder_Y = LabelEncoder()
Y =  labelencoder_Y.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [81]:
# Splitting the datasets into training sets and Test sets 

In [83]:
from sklearn.model_selection import train_test_split

In [85]:
X_train, X_test, Y_train, Y_test = train_test_split( X , Y , test_size = 0.2, random_state = 42)

In [86]:
# Feature Scaling

In [87]:
from sklearn.preprocessing import StandardScaler

In [89]:
sc_X = StandardScaler()
sc_X

StandardScaler()

In [90]:
X_train = sc_X.fit_transform(X_train)
X_train

array([[-1.        ,  1.        , -0.57735027, -0.57735027,  0.        ,
        -0.37796447,  2.64575131, -0.37796447, -0.37796447, -0.37796447,
        -0.37796447, -0.37796447, -0.37796447,  0.        ,  0.        ,
        -0.37796447, -0.37796447,  2.64575131, -0.37796447, -0.37796447,
        -0.37796447, -0.37796447, -0.37796447,  0.        ],
       [-1.        ,  1.        , -0.57735027, -0.57735027,  0.        ,
        -0.37796447, -0.37796447, -0.37796447, -0.37796447, -0.37796447,
        -0.37796447,  2.64575131, -0.37796447,  0.        ,  0.        ,
        -0.37796447, -0.37796447, -0.37796447, -0.37796447, -0.37796447,
        -0.37796447,  2.64575131, -0.37796447,  0.        ],
       [-1.        ,  1.        , -0.57735027, -0.57735027,  0.        ,
        -0.37796447, -0.37796447, -0.37796447, -0.37796447, -0.37796447,
        -0.37796447, -0.37796447,  2.64575131,  0.        ,  0.        ,
        -0.37796447, -0.37796447, -0.37796447, -0.37796447, -0.37796447,
  

In [92]:
X_test = sc_X.fit_transform(X_test)
X_test

array([[ 0.,  0.,  1., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0., -1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        -1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.]])